//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFS.Service.Services
{
    using System;
    using SimpleInjector;
    using WFS.Domain;
    using Entities.Contracts;
    using System.Linq;
    using System.Text;
    using WFS.Entities.Interfaces;
    using WFS.Domain.Query;
    using System.Data;
    using System.Xml;
    using WFS.Entities.Models;
    using WFS.Entities.Enumerations;
    using System.Threading.Tasks;
    using System.Collections.Generic;
    
    public class LogDatabaseService
    {
    	private readonly Container _container;
    	public LogDatabaseService(Container container)
    	{
    		_container = container;
    	}
    
    	    
    	public ServiceResult<LogDatabase> Add(LogDatabase obj)
    	{
    		try
    		{
    			IMediator service = _container.GetInstance<IMediator>();
    			IUserContext currentUser = _container.GetInstance<IUserContext>();
    			obj.IsDeleted = false;
    			var query = new LogDatabaseAddQuery();
    			query.LogDatabase = obj;
    			return new ServiceResult<LogDatabase>(service.Proccess(query), message: ClientErrorMessage.Success(), state: ServiceResultStates.SUCCESS);
    		}
    		catch(ExceptionLog ex)
    		{
    			LoggerService.Logger.Log(_container, ex);
    			return new ServiceResult<LogDatabase>(result: null, message: ClientErrorMessage.Error(), state: ServiceResultStates.ERROR);
    		}
    	}
    	public ServiceResult<LogDatabase> Edit(LogDatabase obj)
    	{
    		try
    		{
    			IMediator service = _container.GetInstance<IMediator>();
    			IUserContext currentUser = _container.GetInstance<IUserContext>();
    			var query = new LogDatabaseEditQuery();
    			query.LogDatabase = obj;
    			return new ServiceResult<LogDatabase>(service.Proccess(query), message: ClientErrorMessage.Success(), state: ServiceResultStates.SUCCESS);
    		}
    		catch(ExceptionLog ex)
    		{
    			LoggerService.Logger.Log(_container, ex);
    			return new ServiceResult<LogDatabase>(result: null, message: ClientErrorMessage.Error(), state: ServiceResultStates.ERROR);
    		}
    	}
    	public ServiceResult<LogDatabase> Retrieve(int Id)
    	{
    		try
    		{
    			IMediator service = _container.GetInstance<IMediator>();
    			var query = new LogDatabaseRetrieveQuery{ Id = Id };
    			return new ServiceResult<LogDatabase>(service.Proccess(query), message: ClientErrorMessage.Success(), state: ServiceResultStates.SUCCESS);
    		}
    		catch(ExceptionLog ex)
    		{
    			LoggerService.Logger.Log(_container, ex);
    			return new ServiceResult<LogDatabase>(result: null, message: ClientErrorMessage.Error(), state: ServiceResultStates.ERROR);
    		}
    	}
    	public ServiceResult<IList<LogDatabase>> GetAll()
    	{
    		try
    		{
    			IMediator service = _container.GetInstance<IMediator>();
    			var query = new LogDatabaseGetAllQuery();
    			return new ServiceResult<IList<LogDatabase>>(service.Proccess(query), message: ClientErrorMessage.Success(), state: ServiceResultStates.SUCCESS);
    		}
    		catch(ExceptionLog ex)
    		{
    			LoggerService.Logger.Log(_container, ex);
    			return new ServiceResult<IList<LogDatabase>>(result: null, message: ClientErrorMessage.Error(), state: ServiceResultStates.ERROR);
    		}
    	}
    	public ServiceResult<string> Delete(int Id)
    	{
    		try
    		{
    			IMediator service = _container.GetInstance<IMediator>();
    			var query = new LogDatabaseDeleteQuery{ Id = Id };
    			return new ServiceResult<string>(service.Proccess(query).ToString(), message: ClientErrorMessage.Success(), state: ServiceResultStates.SUCCESS);
    		}
    		catch(ExceptionLog ex)
    		{
    			LoggerService.Logger.Log(_container, ex);
    			return new ServiceResult<string>(result: null, message: ClientErrorMessage.Error(), state: ServiceResultStates.ERROR);
    		}
    	}
    }
}
