//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFS.WebApi.Controllers
{
    using System;
    using SimpleInjector;
    using WFS.Entities;
    using System.Linq;
    using System.Net;
    using System.Web.Http;
    using System.Net.Http;
    using WFS.Entities.Models;
    using WFS.Service;
    using Entities.Contracts;
    using WFS.WebApi.Attributes;
    using WFS.Service.Services;
    using System.Collections.Generic;
    
    public class CommonUserTypeController : ApiController
    {
    	private readonly Container _container;
    	public CommonUserTypeController(Container container)
     		: base()
    	{
    		_container = container;
    	}
    
    	    
    	[UserAuthorize]
    	[HttpPost]
    	public ServiceResult<CommonUserType> Add(CommonUserType obj)
    	{
    		CommonUserTypeService service = new CommonUserTypeService(_container);
    		return service.Add(obj);
    	}
    	[UserAuthorize]
    	[HttpPost]
    	public ServiceResult<CommonUserType> Edit(CommonUserType obj)
    	{
    		CommonUserTypeService service = new CommonUserTypeService(_container);
    		return service.Edit(obj);
    	}
    	[UserAuthorize]
    	[HttpPost]
    	public ServiceResult<CommonUserType> Retrieve(int Id)
    	{
    		CommonUserTypeService service = new CommonUserTypeService(_container);
    		return service.Retrieve(Id);
    	}
    	[UserAuthorize]
    	[HttpPost]
    	public ServiceResult<IList<CommonUserType>> GetAll()
    	{
    		CommonUserTypeService service = new CommonUserTypeService(_container);
    		return service.GetAll();
    	}
    	[UserAuthorize]
    	[HttpPost]
    	public ServiceResult<string> Delete(int Id)
    	{
    		CommonUserTypeService service = new CommonUserTypeService(_container);
    		return service.Delete(Id);
    	}
    }
}
