//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated from the WFS T4 template.
// Do not change
//
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFS.Entities.Models
{

    using System;
    using System.Collections.Generic;

    public partial class Note
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public string Details { get; set; }

        public string Color { get; set; }

        public string UserId { get; set; }

        public Nullable<bool> IsDeleted { get; set; }

       
    }
}
