//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFS.Domain.Query
{
    using System;
    using WFS.Domain;
    using System.Linq;
    using System.Text;
    using WFS.Domain.Query;
    using System.Data;
    using System.Xml;
    using WFS.Db;
    using Entities.Models;
    using WFS.Entities.Enumerations;
    using AutoMapper;
    using System.Threading.Tasks;
    using System.Collections.Generic;
    
    public class LogDatabaseRetrieveQuery : IQuery<WFS.Entities.Models.LogDatabase>
    {
    	public int Id { get; set; }
    }
    
    public class LogDatabaseRetrieveQueryHandler : IQueryHandler<LogDatabaseRetrieveQuery, WFS.Entities.Models.LogDatabase>
    {
    	private readonly DbEntities _db;
    	public LogDatabaseRetrieveQueryHandler()
    	{
    		_db = new DbEntities();
    	}
    
    	    
    	public WFS.Entities.Models.LogDatabase Handler(LogDatabaseRetrieveQuery query)
    	{
    		try
    		{
    			var result = _db.LogDatabase.Include("User").Where(x => x.IsDeleted == false && x.Id == query.Id).FirstOrDefault();
    			Mapper.CreateMap<WFS.Db.User, WFS.Entities.Models.User>();
    			Mapper.CreateMap<WFS.Db.LogDatabase, WFS.Entities.Models.LogDatabase>().ForMember(c => c.User, d => d.MapFrom(s => s.User));
    			return Mapper.Map<WFS.Db.LogDatabase, WFS.Entities.Models.LogDatabase>(result);
    
    		}
    		catch (Exception ex)
    		{
    			throw new ExceptionLog(LogType.DATABASE_SELECT, LogLevel.ERROR, ex, "RetrieveQueryHandler");
    		}
    	}
    }
}
