//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFS.Domain.Query
{
    using System;
    using WFS.Domain;
    using System.Linq;
    using System.Text;
    using WFS.Domain.Query;
    using System.Data;
    using System.Xml;
    using WFS.Db;
    using Entities.Models;
    using WFS.Entities.Enumerations;
    using AutoMapper;
    using System.Threading.Tasks;
    using System.Collections.Generic;
    
    public class LogLoginGetAllQuery : IQuery<IList<WFS.Entities.Models.LogLogin>>
    {
    	
    }
    
    public class LogLoginGetAllQueryHandler : IQueryHandler<LogLoginGetAllQuery, IList<WFS.Entities.Models.LogLogin>>
    {
    	private readonly DbEntities _db;
    	public LogLoginGetAllQueryHandler()
    	{
    		_db = new DbEntities();
    	}
    
    	    
    	public IList<WFS.Entities.Models.LogLogin> Handler(LogLoginGetAllQuery query)
    	{
    		try
    		{
    			var result = _db.LogLogin.Include("User").Where(x => x.IsDeleted == false).AsEnumerable().ToList();
    			Mapper.CreateMap<WFS.Db.User, WFS.Entities.Models.User>();
    			Mapper.CreateMap<WFS.Db.LogLogin, WFS.Entities.Models.LogLogin>().ForMember(c => c.User, d => d.MapFrom(s => s.User));
    			return Mapper.Map<IEnumerable<WFS.Db.LogLogin>, IEnumerable<WFS.Entities.Models.LogLogin>>(result).ToList();
    
    		}
    		catch (Exception ex)
    		{
    			throw new ExceptionLog(LogType.DATABASE_SELECT, LogLevel.ERROR, ex, "GetAllQueryHandler");
    		}
    	}
    }
    
}
