//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFS.Domain.Query
{
    using System;
    using WFS.Domain;
    using System.Linq;
    using System.Text;
    using WFS.Domain.Query;
    using System.Data;
    using System.Xml;
    using WFS.Db;
    using Entities.Models;
    using WFS.Entities.Enumerations;
    using AutoMapper;
    using System.Threading.Tasks;
    using System.Collections.Generic;
    
    public class LogLoginEditQuery : IQuery<WFS.Entities.Models.LogLogin>
    {
    	public WFS.Entities.Models.LogLogin LogLogin{ get; set; }
    }
    
    public class LogLoginEditQueryHandler : IQueryHandler<LogLoginEditQuery, WFS.Entities.Models.LogLogin>
    {
    	private readonly DbEntities _db;
    	public LogLoginEditQueryHandler()
    	{
    		_db = new DbEntities();
    	}
    
    	    
    	public WFS.Entities.Models.LogLogin Handler(LogLoginEditQuery query)
    	{
    		try
    		{
    			var obj = new WFS.Db.LogLogin();
    			obj = _db.LogLogin.FirstOrDefault(x => x.Id == query.LogLogin.Id);
    			obj.Id = query.LogLogin.Id;
    			obj.UserId = query.LogLogin.UserId;
    			obj.LogDate = query.LogLogin.LogDate;
    			obj.LoginLogType = query.LogLogin.LoginLogType;
    			obj.ExceptionString = query.LogLogin.ExceptionString;
    			obj.Comment = query.LogLogin.Comment;
                obj.IsDeleted = query.LogLogin.IsDeleted;
    			_db.SaveChanges();
    			return query.LogLogin;
    
    		}
    		catch (Exception ex)
    		{
    			throw new ExceptionLog(LogType.DATABASE_UPDATE, LogLevel.ERROR, ex, "EditQueryHandler");
    		}
    	}
    }
    
}
