//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFS.Domain.Query
{
    using System;
    using WFS.Domain;
    using System.Linq;
    using System.Text;
    using WFS.Domain.Query;
    using System.Data;
    using System.Xml;
    using WFS.Db;
    using Entities.Models;
    using WFS.Entities.Enumerations;
    using AutoMapper;
    using System.Threading.Tasks;
    using System.Collections.Generic;

    public class NoteRetrieveQuery : IQuery<WFS.Entities.Models.Note>
    {
        public int Id { get; set; }
    }

    public class NoteRetrieveQueryHandler : IQueryHandler<NoteRetrieveQuery, WFS.Entities.Models.Note>
    {
        private readonly DbEntities _db;
        public NoteRetrieveQueryHandler()
        {
            _db = new DbEntities();
        }


        public WFS.Entities.Models.Note Handler(NoteRetrieveQuery query)
        {
            try
            {
                var result = _db.Note.Where(x => x.IsDeleted == false && x.Id == query.Id).FirstOrDefault();
                Mapper.CreateMap<WFS.Db.Note, WFS.Entities.Models.Note>();
                return Mapper.Map<WFS.Db.Note, WFS.Entities.Models.Note>(result);

            }
            catch (Exception ex)
            {
                throw new ExceptionLog(LogType.DATABASE_SELECT, LogLevel.ERROR, ex, "RetrieveQueryHandler");
            }
        }
    }
}
