//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFS.Domain.Query
{
    using System;
    using WFS.Domain;
    using System.Linq;
    using System.Text;
    using WFS.Domain.Query;
    using System.Data;
    using System.Xml;
    using WFS.Db;
    using Entities.Models;
    using WFS.Entities.Enumerations;
    using AutoMapper;
    using System.Threading.Tasks;
    using System.Collections.Generic;

    public class NoteEditQuery : IQuery<WFS.Entities.Models.Note>
    {
        public WFS.Entities.Models.Note Note { get; set; }
    }

    public class NoteEditQueryHandler : IQueryHandler<NoteEditQuery, WFS.Entities.Models.Note>
    {
        private readonly DbEntities _db;
        public NoteEditQueryHandler()
        {
            _db = new DbEntities();
        }


        public WFS.Entities.Models.Note Handler(NoteEditQuery query)
        {
            try
            {
                var obj = new WFS.Db.Note();
                obj = _db.Note.FirstOrDefault(x => x.Id == query.Note.Id);
                obj.Id = query.Note.Id;
                obj.Name = query.Note.Name;
                obj.Details = query.Note.Details;
                obj.Color = query.Note.Color;
                obj.IsDeleted = query.Note.IsDeleted;
                _db.SaveChanges();
                return query.Note;

            }
            catch (Exception ex)
            {
                throw new ExceptionLog(LogType.DATABASE_UPDATE, LogLevel.ERROR, ex, "EditQueryHandler");
            }
        }
    }

}
