//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFS.Domain.Query
{
    using System;
    using WFS.Domain;
    using System.Linq;
    using System.Text;
    using WFS.Domain.Query;
    using System.Data;
    using System.Xml;
    using WFS.Db;
    using Entities.Models;
    using WFS.Entities.Enumerations;
    using AutoMapper;
    using System.Threading.Tasks;
    using System.Collections.Generic;

    public class NoteAddQuery : IQuery<WFS.Entities.Models.Note>
    {
        public WFS.Entities.Models.Note Note { get; set; }
    }

    public class NoteAddQueryHandler : IQueryHandler<NoteAddQuery, WFS.Entities.Models.Note>
    {
        private readonly DbEntities _db;
        public NoteAddQueryHandler()
        {
            _db = new DbEntities();
        }


        public WFS.Entities.Models.Note Handler(NoteAddQuery query)
        {
            try
            {
                var obj = new WFS.Db.Note();
                obj.Id = query.Note.Id;
                obj.Name = query.Note.Name;
                obj.Details = query.Note.Details;
                obj.Color = string.IsNullOrEmpty(query.Note.Color)? "blue": query.Note.Color;
                //obj.UserId = CurrentUser;
                obj.IsDeleted = string.IsNullOrEmpty(query.Note.IsDeleted.ToString())?false: query.Note.IsDeleted;
                _db.Note.Add(obj);
                _db.SaveChanges();
                query.Note.Id = obj.Id;
                return query.Note;

            }
            catch (Exception ex)
            {
                throw new ExceptionLog(LogType.DATABASE_INSERT, LogLevel.ERROR, ex, "AddQueryHandler");
            }
        }
    }


}
