//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFS.Domain.Query
{
    using System;
    using WFS.Domain;
    using System.Linq;
    using System.Text;
    using WFS.Domain.Query;
    using System.Data;
    using System.Xml;
    using WFS.Db;
    using Entities.Models;
    using WFS.Entities.Enumerations;
    using AutoMapper;
    using System.Threading.Tasks;
    using System.Collections.Generic;

    public class NoteGetAllQuerybyOption : IQuery<IList<WFS.Entities.Models.Note>>
    {
        public string Option { get; set; }
    }

    public class NoteGetAllQuerybyOptionHandler : IQueryHandler<NoteGetAllQuerybyOption, IList<WFS.Entities.Models.Note>>
    {
        private readonly DbEntities _db;
        public NoteGetAllQuerybyOptionHandler()
        {
            _db = new DbEntities();
        }


        public IList<WFS.Entities.Models.Note> Handler(NoteGetAllQuerybyOption query)
        {
            try
            {
               var result = _db.Note.Where(x => x.IsDeleted == false).Where(x => query.Option.ToLower().Contains(x.Color)).AsEnumerable().ToList();
                Mapper.CreateMap<WFS.Db.Note, WFS.Entities.Models.Note>();
                return Mapper.Map<IEnumerable<WFS.Db.Note>, IEnumerable<WFS.Entities.Models.Note>>(result).ToList();

            }
            catch (Exception ex)
            {
                throw new ExceptionLog(LogType.DATABASE_SELECT, LogLevel.ERROR, ex, "GetAllQueryHandler");
            }
        }
    }

}
