//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFS.Domain.Query
{
    using System;
    using WFS.Domain;
    using System.Linq;
    using System.Text;
    using WFS.Domain.Query;
    using System.Data;
    using System.Xml;
    using WFS.Db;
    using Entities.Models;
    using WFS.Entities.Enumerations;
    using AutoMapper;
    using System.Threading.Tasks;
    using System.Collections.Generic;

    public class UserRetrieveQuery : IQuery<WFS.Entities.Models.User>
    {
        public int Id { get; set; }
    }

    public class UserRetrieveQueryHandler : IQueryHandler<UserRetrieveQuery, WFS.Entities.Models.User>
    {
        private readonly DbEntities _db;
        public UserRetrieveQueryHandler()
        {
            _db = new DbEntities();
        }


        public WFS.Entities.Models.User Handler(UserRetrieveQuery query)
        {
            try
            {
                var result = _db.User.Include("CommonUserType").Include("User2").Include("User3").Where(x => x.IsDeleted == false && x.Id == query.Id).FirstOrDefault();
                Mapper.CreateMap<WFS.Db.CommonUserType, WFS.Entities.Models.CommonUserType>();
                Mapper.CreateMap<WFS.Db.User, WFS.Entities.Models.User>();
                Mapper.CreateMap<WFS.Db.User, WFS.Entities.Models.User>();
                Mapper.CreateMap<WFS.Db.User, WFS.Entities.Models.User>().ForMember(c => c.CommonUserType, d => d.MapFrom(s => s.CommonUserType)).ForMember(c => c.User2, d => d.MapFrom(s => s.User2)).ForMember(c => c.User3, d => d.MapFrom(s => s.User3));
                return Mapper.Map<WFS.Db.User, WFS.Entities.Models.User>(result);

            }
            catch (Exception ex)
            {
                throw new ExceptionLog(LogType.DATABASE_SELECT, LogLevel.ERROR, ex, "RetrieveQueryHandler");
            }
        }
    }
}
